/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package calculadora;

import com.sun.awt.AWTUtilities;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author JOHN EDWAR
 */
public class interfazCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form interfazCalculadora
     */
    private int x;
    private int y;
    private int controlMemoria = 0;
    private String ultimoSigno = "";
    private int reescribible = 1; 
    private int operacionNobasica = 0;

    Calculadora dato = new Calculadora();

    public interfazCalculadora() {

        initComponents();
        this.setLocationRelativeTo(null);
//        AWTUtilities.setWindowOpaque(this, false);

        jBmc.setEnabled(false);
        jBMr.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLNumero = new javax.swing.JLabel();
        jLOperaciones = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBModulo = new javax.swing.JButton();
        jBRaiz = new javax.swing.JButton();
        jBElevar = new javax.swing.JButton();
        jBFraccionar = new javax.swing.JButton();
        jBCe = new javax.swing.JButton();
        jBC = new javax.swing.JButton();
        jBBorrar = new javax.swing.JButton();
        jBDivision = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jBMultiplicacion = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jBResta = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jBSuma = new javax.swing.JButton();
        jBNegacion = new javax.swing.JButton();
        jB0 = new javax.swing.JButton();
        jBComa = new javax.swing.JButton();
        jBIgual = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jBMinimizar = new javax.swing.JButton();
        jBCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jBmc = new javax.swing.JButton();
        jBmMas = new javax.swing.JButton();
        jBmMenos = new javax.swing.JButton();
        jBm = new javax.swing.JButton();
        jBMr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(45, 44, 44));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNumero.setFont(new java.awt.Font("Tahoma", 0, 70)); // NOI18N
        jLNumero.setForeground(new java.awt.Color(255, 255, 255));
        jLNumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLNumero.setText("0");
        jPanel1.add(jLNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 580, 120));

        jLOperaciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLOperaciones.setForeground(new java.awt.Color(255, 255, 255));
        jLOperaciones.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 580, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 610, 220));

        jPanel2.setBackground(new java.awt.Color(25, 24, 24));
        jPanel2.setLayout(new java.awt.GridLayout(6, 4, 3, 3));

        jBModulo.setBackground(new java.awt.Color(25, 24, 24));
        jBModulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBModulo.setForeground(new java.awt.Color(255, 255, 255));
        jBModulo.setText("%");
        jBModulo.setContentAreaFilled(false);
        jBModulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBModulo.setFocusPainted(false);
        jBModulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBModulo.setOpaque(true);
        jBModulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBModuloMouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBModuloMouseExited(evt);
            }
        });
        jBModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModuloActionPerformed(evt);
            }
        });
        jPanel2.add(jBModulo);

        jBRaiz.setBackground(new java.awt.Color(25, 24, 24));
        jBRaiz.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBRaiz.setForeground(new java.awt.Color(255, 255, 255));
        jBRaiz.setText("√");
        jBRaiz.setContentAreaFilled(false);
        jBRaiz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBRaiz.setFocusPainted(false);
        jBRaiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBRaiz.setOpaque(true);
        jBRaiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBRaizMouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBRaizMouseExited(evt);
            }
        });
        jBRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRaizActionPerformed(evt);
            }
        });
        jPanel2.add(jBRaiz);

        jBElevar.setBackground(new java.awt.Color(25, 24, 24));
        jBElevar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBElevar.setForeground(new java.awt.Color(255, 255, 255));
        jBElevar.setText("x²");
        jBElevar.setContentAreaFilled(false);
        jBElevar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBElevar.setFocusPainted(false);
        jBElevar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBElevar.setOpaque(true);
        jBElevar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBElevarMouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBElevarMouseExited(evt);
            }
        });
        jBElevar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBElevarActionPerformed(evt);
            }
        });
        jPanel2.add(jBElevar);

        jBFraccionar.setBackground(new java.awt.Color(25, 24, 24));
        jBFraccionar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBFraccionar.setForeground(new java.awt.Color(255, 255, 255));
        jBFraccionar.setText("¹/ꭙ");
        jBFraccionar.setContentAreaFilled(false);
        jBFraccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBFraccionar.setFocusPainted(false);
        jBFraccionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBFraccionar.setOpaque(true);
        jBFraccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBFraccionarMouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBFraccionarMouseExited(evt);
            }
        });
        jBFraccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFraccionarActionPerformed(evt);
            }
        });
        jPanel2.add(jBFraccionar);

        jBCe.setBackground(new java.awt.Color(25, 24, 24));
        jBCe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBCe.setForeground(new java.awt.Color(255, 255, 255));
        jBCe.setText("CE");
        jBCe.setContentAreaFilled(false);
        jBCe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCe.setFocusPainted(false);
        jBCe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBCe.setOpaque(true);
        jBCe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBCeMouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBCeMouseExited(evt);
            }
        });
        jBCe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCeActionPerformed(evt);
            }
        });
        jPanel2.add(jBCe);

        jBC.setBackground(new java.awt.Color(25, 24, 24));
        jBC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBC.setForeground(new java.awt.Color(255, 255, 255));
        jBC.setText("C");
        jBC.setContentAreaFilled(false);
        jBC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBC.setFocusPainted(false);
        jBC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBC.setOpaque(true);
        jBC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBCMouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBCMouseExited(evt);
            }
        });
        jBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCActionPerformed(evt);
            }
        });
        jPanel2.add(jBC);

        jBBorrar.setBackground(new java.awt.Color(25, 24, 24));
        jBBorrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBBorrar.setForeground(new java.awt.Color(255, 255, 255));
        jBBorrar.setText("◄");
        jBBorrar.setContentAreaFilled(false);
        jBBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBBorrar.setFocusPainted(false);
        jBBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBBorrar.setOpaque(true);
        jBBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBBorrarMouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBBorrarMouseExited(evt);
            }
        });
        jBBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(jBBorrar);

        jBDivision.setBackground(new java.awt.Color(25, 24, 24));
        jBDivision.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBDivision.setForeground(new java.awt.Color(255, 255, 255));
        jBDivision.setText("÷");
        jBDivision.setContentAreaFilled(false);
        jBDivision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBDivision.setFocusPainted(false);
        jBDivision.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBDivision.setOpaque(true);
        jBDivision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBDivisionMouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBDivisionMouseExited(evt);
            }
        });
        jBDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDivisionActionPerformed(evt);
            }
        });
        jPanel2.add(jBDivision);

        jB7.setBackground(new java.awt.Color(51, 51, 51));
        jB7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jB7.setForeground(new java.awt.Color(255, 255, 255));
        jB7.setText("7");
        jB7.setContentAreaFilled(false);
        jB7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB7.setFocusPainted(false);
        jB7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB7.setOpaque(true);
        jB7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jB7MouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jB7MouseExited(evt);
            }
        });
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });
        jB7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jB7KeyPressed(evt);
            }
        });
        jPanel2.add(jB7);

        jB8.setBackground(new java.awt.Color(51, 51, 51));
        jB8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jB8.setForeground(new java.awt.Color(255, 255, 255));
        jB8.setText("8");
        jB8.setContentAreaFilled(false);
        jB8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB8.setFocusPainted(false);
        jB8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB8.setOpaque(true);
        jB8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jB8MouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jB8MouseExited(evt);
            }
        });
        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB8ActionPerformed(evt);
            }
        });
        jPanel2.add(jB8);

        jB9.setBackground(new java.awt.Color(51, 51, 51));
        jB9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jB9.setForeground(new java.awt.Color(255, 255, 255));
        jB9.setText("9");
        jB9.setContentAreaFilled(false);
        jB9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB9.setFocusPainted(false);
        jB9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB9.setOpaque(true);
        jB9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jB9MouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jB9MouseExited(evt);
            }
        });
        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB9ActionPerformed(evt);
            }
        });
        jPanel2.add(jB9);

        jBMultiplicacion.setBackground(new java.awt.Color(25, 24, 24));
        jBMultiplicacion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBMultiplicacion.setForeground(new java.awt.Color(255, 255, 255));
        jBMultiplicacion.setText("×");
        jBMultiplicacion.setContentAreaFilled(false);
        jBMultiplicacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBMultiplicacion.setFocusPainted(false);
        jBMultiplicacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBMultiplicacion.setOpaque(true);
        jBMultiplicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBMultiplicacionMouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBMultiplicacionMouseExited(evt);
            }
        });
        jBMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMultiplicacionActionPerformed(evt);
            }
        });
        jPanel2.add(jBMultiplicacion);

        jB4.setBackground(new java.awt.Color(51, 51, 51));
        jB4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jB4.setForeground(new java.awt.Color(255, 255, 255));
        jB4.setText("4");
        jB4.setContentAreaFilled(false);
        jB4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB4.setFocusPainted(false);
        jB4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB4.setOpaque(true);
        jB4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jB4MouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jB4MouseExited(evt);
            }
        });
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });
        jPanel2.add(jB4);

        jB5.setBackground(new java.awt.Color(51, 51, 51));
        jB5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jB5.setForeground(new java.awt.Color(255, 255, 255));
        jB5.setText("5");
        jB5.setContentAreaFilled(false);
        jB5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB5.setFocusPainted(false);
        jB5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB5.setOpaque(true);
        jB5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jB5MouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jB5MouseExited(evt);
            }
        });
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });
        jPanel2.add(jB5);

        jB6.setBackground(new java.awt.Color(51, 51, 51));
        jB6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jB6.setForeground(new java.awt.Color(255, 255, 255));
        jB6.setText("6");
        jB6.setContentAreaFilled(false);
        jB6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB6.setFocusPainted(false);
        jB6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB6.setOpaque(true);
        jB6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jB6MouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jB6MouseExited(evt);
            }
        });
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });
        jPanel2.add(jB6);

        jBResta.setBackground(new java.awt.Color(25, 24, 24));
        jBResta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBResta.setForeground(new java.awt.Color(255, 255, 255));
        jBResta.setText("-");
        jBResta.setContentAreaFilled(false);
        jBResta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBResta.setFocusPainted(false);
        jBResta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBResta.setOpaque(true);
        jBResta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBRestaMouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBRestaMouseExited(evt);
            }
        });
        jBResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRestaActionPerformed(evt);
            }
        });
        jPanel2.add(jBResta);

        jB1.setBackground(new java.awt.Color(51, 51, 51));
        jB1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jB1.setForeground(new java.awt.Color(255, 255, 255));
        jB1.setText("1");
        jB1.setContentAreaFilled(false);
        jB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB1.setFocusPainted(false);
        jB1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB1.setOpaque(true);
        jB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jB1MouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jB1MouseExited(evt);
            }
        });
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });
        jPanel2.add(jB1);

        jB2.setBackground(new java.awt.Color(51, 51, 51));
        jB2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jB2.setForeground(new java.awt.Color(255, 255, 255));
        jB2.setText("2");
        jB2.setContentAreaFilled(false);
        jB2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB2.setFocusPainted(false);
        jB2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB2.setOpaque(true);
        jB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jB2MouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jB2MouseExited(evt);
            }
        });
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });
        jPanel2.add(jB2);

        jB3.setBackground(new java.awt.Color(51, 51, 51));
        jB3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jB3.setForeground(new java.awt.Color(255, 255, 255));
        jB3.setText("3");
        jB3.setContentAreaFilled(false);
        jB3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB3.setFocusPainted(false);
        jB3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB3.setOpaque(true);
        jB3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jB3MouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jB3MouseExited(evt);
            }
        });
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });
        jPanel2.add(jB3);

        jBSuma.setBackground(new java.awt.Color(25, 24, 24));
        jBSuma.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBSuma.setForeground(new java.awt.Color(255, 255, 255));
        jBSuma.setText("+");
        jBSuma.setContentAreaFilled(false);
        jBSuma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSuma.setFocusPainted(false);
        jBSuma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSuma.setOpaque(true);
        jBSuma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBSumaMouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBSumaMouseExited(evt);
            }
        });
        jBSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSumaActionPerformed(evt);
            }
        });
        jPanel2.add(jBSuma);

        jBNegacion.setBackground(new java.awt.Color(25, 24, 24));
        jBNegacion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBNegacion.setForeground(new java.awt.Color(255, 255, 255));
        jBNegacion.setText("±");
        jBNegacion.setContentAreaFilled(false);
        jBNegacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBNegacion.setFocusPainted(false);
        jBNegacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBNegacion.setOpaque(true);
        jBNegacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBNegacionMouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBNegacionMouseExited(evt);
            }
        });
        jPanel2.add(jBNegacion);

        jB0.setBackground(new java.awt.Color(51, 51, 51));
        jB0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jB0.setForeground(new java.awt.Color(255, 255, 255));
        jB0.setText("0");
        jB0.setContentAreaFilled(false);
        jB0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB0.setFocusPainted(false);
        jB0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB0.setOpaque(true);
        jB0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jB0MouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jB0MouseExited(evt);
            }
        });
        jB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB0ActionPerformed(evt);
            }
        });
        jPanel2.add(jB0);

        jBComa.setBackground(new java.awt.Color(25, 24, 24));
        jBComa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBComa.setForeground(new java.awt.Color(255, 255, 255));
        jBComa.setText(",");
        jBComa.setContentAreaFilled(false);
        jBComa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBComa.setFocusPainted(false);
        jBComa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBComa.setOpaque(true);
        jBComa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBComaMouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBComaMouseExited(evt);
            }
        });
        jBComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBComaActionPerformed(evt);
            }
        });
        jPanel2.add(jBComa);

        jBIgual.setBackground(new java.awt.Color(25, 24, 24));
        jBIgual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBIgual.setForeground(new java.awt.Color(255, 255, 255));
        jBIgual.setText("=");
        jBIgual.setContentAreaFilled(false);
        jBIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBIgual.setFocusPainted(false);
        jBIgual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBIgual.setOpaque(true);
        jBIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBIgualMouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBIgualMouseExited(evt);
            }
        });
        jBIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIgualActionPerformed(evt);
            }
        });
        jPanel2.add(jBIgual);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 610, 360));

        jPanel3.setBackground(new java.awt.Color(45, 44, 44));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBMinimizar.setBackground(new java.awt.Color(0, 0, 0));
        jBMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimizar_blanco.png"))); // NOI18N
        jBMinimizar.setToolTipText("");
        jBMinimizar.setBorderPainted(false);
        jBMinimizar.setContentAreaFilled(false);
        jBMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBMinimizar.setFocusPainted(false);
        jBMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMinimizarActionPerformed(evt);
            }
        });
        jPanel3.add(jBMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 50, 30));

        jBCerrar.setBackground(new java.awt.Color(0, 0, 0));
        jBCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jBCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar_blanco.png"))); // NOI18N
        jBCerrar.setToolTipText("");
        jBCerrar.setBorderPainted(false);
        jBCerrar.setContentAreaFilled(false);
        jBCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCerrar.setFocusPainted(false);
        jBCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });
        jPanel3.add(jBCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 50, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Calculadora");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 70));

        jPanel4.setBackground(new java.awt.Color(25, 24, 24));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jBmc.setBackground(new java.awt.Color(0, 0, 0));
        jBmc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBmc.setForeground(new java.awt.Color(255, 255, 255));
        jBmc.setText("MC");
        jBmc.setContentAreaFilled(false);
        jBmc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBmc.setFocusPainted(false);
        jBmc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBmc.setOpaque(true);
        jBmc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBmcMouseEntered1(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBmcMouseExited1(evt);
            }
        });
        jBmc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmcActionPerformed(evt);
            }
        });
        jPanel4.add(jBmc);

        jBmMas.setBackground(new java.awt.Color(25, 24, 24));
        jBmMas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBmMas.setForeground(new java.awt.Color(255, 255, 255));
        jBmMas.setText("M+");
        jBmMas.setContentAreaFilled(false);
        jBmMas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBmMas.setFocusPainted(false);
        jBmMas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBmMas.setOpaque(true);
        jBmMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBmMasMouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBmMasMouseExited(evt);
            }
        });
        jBmMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmMasActionPerformed(evt);
            }
        });
        jPanel4.add(jBmMas);

        jBmMenos.setBackground(new java.awt.Color(25, 24, 24));
        jBmMenos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBmMenos.setForeground(new java.awt.Color(255, 255, 255));
        jBmMenos.setText("M-");
        jBmMenos.setContentAreaFilled(false);
        jBmMenos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBmMenos.setFocusPainted(false);
        jBmMenos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBmMenos.setOpaque(true);
        jBmMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBmMenosMouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBmMenosMouseExited(evt);
            }
        });
        jBmMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmMenosActionPerformed(evt);
            }
        });
        jPanel4.add(jBmMenos);

        jBm.setBackground(new java.awt.Color(25, 24, 24));
        jBm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBm.setForeground(new java.awt.Color(255, 255, 255));
        jBm.setText("M");
        jBm.setContentAreaFilled(false);
        jBm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBm.setFocusPainted(false);
        jBm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBm.setOpaque(true);
        jBm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBmMouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBmMouseExited(evt);
            }
        });
        jBm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmActionPerformed(evt);
            }
        });
        jPanel4.add(jBm);

        jBMr.setBackground(new java.awt.Color(0, 0, 0));
        jBMr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBMr.setForeground(new java.awt.Color(255, 255, 255));
        jBMr.setText("MR");
        jBMr.setContentAreaFilled(false);
        jBMr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBMr.setFocusPainted(false);
        jBMr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBMr.setOpaque(true);
        jBMr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBMrMouseEntered(evt);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBMrMouseExited(evt);
            }
        });
        jBMr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMrActionPerformed(evt);
            }
        });
        jPanel4.add(jBMr);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 610, 60));

        pack();
    } // </editor-fold>//GEN-END:initComponents

    private void jBMinimizarActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jBMinimizarActionPerformed
        this.setExtendedState(ICONIFIED);
    } //GEN-LAST:event_jBMinimizarActionPerformed

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jBCerrarActionPerformed
        System.exit(0);
    } //GEN-LAST:event_jBCerrarActionPerformed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
     }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jB7ActionPerformed

        if (reescribible == 1) {
            reescribible = 0;
            jLNumero.setText("7");
        } else {
            jLNumero.setText(jLNumero.getText() + "7");
        }

    } //GEN-LAST:event_jB7ActionPerformed

    private void jBRestaActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jBRestaActionPerformed

        reescribible = 1;

        if (ultimoSigno.equals("")) {
            dato.setNumero(Double.parseDouble(jLNumero.getText()));
            System.out.println("datico" + dato.getNumero());
            jLOperaciones.setText(jLNumero.getText() + " -");
            reescribible = 1;
        } else if (reescribible != 0) {
            System.out.println("-----------------------------------");
            System.out.println("datico" + dato.getNumero());
            System.out.println("ultimo signo" + ultimoSigno);
            jLOperaciones.setText(jLOperaciones.getText() + jLNumero.getText() + " -");
            jLNumero.setText(dato.operaciones(Double.parseDouble(jLNumero.getText()), ultimoSigno));

        }

        ultimoSigno = "-";
    } //GEN-LAST:event_jBRestaActionPerformed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    } //GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);

    } //GEN-LAST:event_jPanel3MouseDragged

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jB2ActionPerformed

        if (reescribible == 1) {
            reescribible = 0;
            jLNumero.setText("2");
        } else {
            jLNumero.setText(jLNumero.getText() + "2");
        }
    } //GEN-LAST:event_jB2ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jB4ActionPerformed

        if (reescribible == 1) {
            reescribible = 0;
            jLNumero.setText("4");
        } else {
            jLNumero.setText(jLNumero.getText() + "4");
        }

    } //GEN-LAST:event_jB4ActionPerformed

    private void jB8ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jB8ActionPerformed

        if (reescribible == 1) {
            reescribible = 0;
            jLNumero.setText("8");
        } else {
            jLNumero.setText(jLNumero.getText() + "8");
        }
    } //GEN-LAST:event_jB8ActionPerformed

    private void jB8MouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB8MouseEntered
        // TODO add your handling code here:
        jB8.setBackground(new Color(102, 102, 102));
    } //GEN-LAST:event_jB8MouseEntered

    private void jB8MouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB8MouseExited
        // TODO add your handling code here:
        jB8.setBackground(new Color(51, 51, 51));
    } //GEN-LAST:event_jB8MouseExited

    private void jB7MouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB7MouseEntered
        // TODO add your handling code here:
        jB7.setBackground(new Color(102, 102, 102));
    } //GEN-LAST:event_jB7MouseEntered

    private void jB7MouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB7MouseExited
        // TODO add your handling code here:
        jB7.setBackground(new Color(51, 51, 51));
    } //GEN-LAST:event_jB7MouseExited

    private void jB9MouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB9MouseEntered
        jB9.setBackground(new Color(102, 102, 102));
    } //GEN-LAST:event_jB9MouseEntered

    private void jB9MouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB9MouseExited
        jB9.setBackground(new Color(51, 51, 51));
    } //GEN-LAST:event_jB9MouseExited

    private void jB4MouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB4MouseEntered
        jB4.setBackground(new Color(102, 102, 102));
    } //GEN-LAST:event_jB4MouseEntered

    private void jB4MouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB4MouseExited
        jB4.setBackground(new Color(51, 51, 51));
    } //GEN-LAST:event_jB4MouseExited

    private void jB5MouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB5MouseEntered
        jB5.setBackground(new Color(102, 102, 102));
    } //GEN-LAST:event_jB5MouseEntered

    private void jB5MouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB5MouseExited
        jB5.setBackground(new Color(51, 51, 51));
    } //GEN-LAST:event_jB5MouseExited

    private void jB6MouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB6MouseEntered
        jB6.setBackground(new Color(102, 102, 102));
    } //GEN-LAST:event_jB6MouseEntered

    private void jB6MouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB6MouseExited
        jB6.setBackground(new Color(51, 51, 51));
    } //GEN-LAST:event_jB6MouseExited

    private void jB1MouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB1MouseEntered
        jB1.setBackground(new Color(102, 102, 102));
    } //GEN-LAST:event_jB1MouseEntered

    private void jB1MouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB1MouseExited
        jB1.setBackground(new Color(51, 51, 51));
    } //GEN-LAST:event_jB1MouseExited

    private void jB2MouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB2MouseEntered
        jB2.setBackground(new Color(102, 102, 102));
    } //GEN-LAST:event_jB2MouseEntered

    private void jB2MouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB2MouseExited
        jB2.setBackground(new Color(51, 51, 51));
    } //GEN-LAST:event_jB2MouseExited

    private void jB3MouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB3MouseEntered
        jB3.setBackground(new Color(102, 102, 102));
    } //GEN-LAST:event_jB3MouseEntered

    private void jB3MouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB3MouseExited
        jB3.setBackground(new Color(51, 51, 51));
    } //GEN-LAST:event_jB3MouseExited

    private void jB0MouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB0MouseEntered
        jB0.setBackground(new Color(102, 102, 102));
    } //GEN-LAST:event_jB0MouseEntered

    private void jB0MouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jB0MouseExited
        jB0.setBackground(new Color(51, 51, 51));
    } //GEN-LAST:event_jB0MouseExited

    private void jBDivisionMouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBDivisionMouseEntered
        jBDivision.setBackground(new Color(0, 51, 204));
    } //GEN-LAST:event_jBDivisionMouseEntered

    private void jBDivisionMouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBDivisionMouseExited
        jBDivision.setBackground(new Color(25, 24, 24));
    } //GEN-LAST:event_jBDivisionMouseExited

    private void jBMultiplicacionMouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBMultiplicacionMouseEntered
        jBMultiplicacion.setBackground(new Color(0, 51, 204));
    } //GEN-LAST:event_jBMultiplicacionMouseEntered

    private void jBMultiplicacionMouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBMultiplicacionMouseExited
        jBMultiplicacion.setBackground(new Color(25, 24, 24));
    } //GEN-LAST:event_jBMultiplicacionMouseExited

    private void jBRestaMouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBRestaMouseEntered
        jBResta.setBackground(new Color(0, 51, 204));
    } //GEN-LAST:event_jBRestaMouseEntered

    private void jBRestaMouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBRestaMouseExited
        jBResta.setBackground(new Color(25, 24, 24));
    } //GEN-LAST:event_jBRestaMouseExited

    private void jBSumaMouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBSumaMouseEntered
        jBSuma.setBackground(new Color(0, 51, 204));
    } //GEN-LAST:event_jBSumaMouseEntered

    private void jBSumaMouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBSumaMouseExited
        jBSuma.setBackground(new Color(25, 24, 24));
    } //GEN-LAST:event_jBSumaMouseExited

    private void jBIgualMouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBIgualMouseEntered
        jBIgual.setBackground(new Color(0, 51, 204));
    } //GEN-LAST:event_jBIgualMouseEntered

    private void jBIgualMouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBIgualMouseExited
        jBIgual.setBackground(new Color(25, 24, 24));
    } //GEN-LAST:event_jBIgualMouseExited

    private void jBmcMouseEntered1(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBmcMouseEntered1

        if (controlMemoria != 0) {

            jBmc.setBackground(new Color(51, 51, 51));
        }
    } //GEN-LAST:event_jBmcMouseEntered1

    private void jBmcMouseExited1(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBmcMouseExited1
        if (controlMemoria != 0) {

            jBmc.setBackground(new Color(25, 24, 24));
        }
    } //GEN-LAST:event_jBmcMouseExited1

    private void jBmMasMouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBmMasMouseEntered
        jBmMas.setBackground(new Color(51, 51, 51));
    } //GEN-LAST:event_jBmMasMouseEntered

    private void jBmMasMouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBmMasMouseExited
        jBmMas.setBackground(new Color(25, 24, 24));
    } //GEN-LAST:event_jBmMasMouseExited

    private void jBmMenosMouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBmMenosMouseEntered
        jBmMenos.setBackground(new Color(51, 51, 51));
    } //GEN-LAST:event_jBmMenosMouseEntered

    private void jBmMenosMouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBmMenosMouseExited
        jBmMenos.setBackground(new Color(25, 24, 24));
    } //GEN-LAST:event_jBmMenosMouseExited

    private void jBMrMouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBMrMouseEntered

        if (controlMemoria != 0) {

            jBMr.setBackground(new Color(51, 51, 51));
        }

    } //GEN-LAST:event_jBMrMouseEntered

    private void jBMrMouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBMrMouseExited

        if (controlMemoria != 0) {

            jBMr.setBackground(new Color(25, 24, 24));
        }

    } //GEN-LAST:event_jBMrMouseExited

    private void jBModuloMouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBModuloMouseEntered
        jBModulo.setBackground(new Color(51, 51, 51));
    } //GEN-LAST:event_jBModuloMouseEntered

    private void jBModuloMouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBModuloMouseExited
        jBModulo.setBackground(new Color(25, 24, 24));
    } //GEN-LAST:event_jBModuloMouseExited

    private void jBRaizMouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBRaizMouseEntered
        jBRaiz.setBackground(new Color(51, 51, 51));
    } //GEN-LAST:event_jBRaizMouseEntered

    private void jBRaizMouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBRaizMouseExited
        jBRaiz.setBackground(new Color(25, 24, 24));
    } //GEN-LAST:event_jBRaizMouseExited

    private void jBElevarMouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBElevarMouseEntered
        jBElevar.setBackground(new Color(51, 51, 51));
    } //GEN-LAST:event_jBElevarMouseEntered

    private void jBElevarMouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBElevarMouseExited
        jBElevar.setBackground(new Color(25, 24, 24));
    } //GEN-LAST:event_jBElevarMouseExited

    private void jBFraccionarMouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBFraccionarMouseEntered
        jBFraccionar.setBackground(new Color(51, 51, 51));
    } //GEN-LAST:event_jBFraccionarMouseEntered

    private void jBFraccionarMouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBFraccionarMouseExited
        jBFraccionar.setBackground(new Color(25, 24, 24));
    } //GEN-LAST:event_jBFraccionarMouseExited

    private void jBCeMouseEntered(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBCeMouseEntered
        jBCe.setBackground(new Color(51, 51, 51));
    } //GEN-LAST:event_jBCeMouseEntered

    private void jBCeMouseExited(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jBCeMouseExited
        jBCe.setBackground(new Color(25, 24, 24));
    } //GEN-LAST:event_jBCeMouseExited

    private void jBCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCMouseEntered
        jBC.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jBCMouseEntered

    private void jBCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCMouseExited
        jBC.setBackground(new Color(25, 24, 24));
    }//GEN-LAST:event_jBCMouseExited

    private void jBBorrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBorrarMouseEntered
        jBBorrar.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jBBorrarMouseEntered

    private void jBBorrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBorrarMouseExited
        jBBorrar.setBackground(new Color(25, 24, 24));
    }//GEN-LAST:event_jBBorrarMouseExited

    private void jBComaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBComaMouseEntered
        jBComa.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jBComaMouseEntered

    private void jBComaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBComaMouseExited
        jBComa.setBackground(new Color(25, 24, 24));
    }//GEN-LAST:event_jBComaMouseExited

    private void jBNegacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBNegacionMouseEntered
        jBNegacion.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jBNegacionMouseEntered

    private void jBNegacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBNegacionMouseExited
        jBNegacion.setBackground(new Color(25, 24, 24));
    }//GEN-LAST:event_jBNegacionMouseExited

    private void jBmMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmMasActionPerformed

        jBmc.setEnabled(true);
        jBMr.setEnabled(true);
        jBmc.setBackground(new Color(25, 24, 24));
        jBMr.setBackground(new Color(25, 24, 24));
        controlMemoria = 1;
        dato.operacionMemoria(1, jLNumero.getText());
    }//GEN-LAST:event_jBmMasActionPerformed

    private void jBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCActionPerformed
        ultimoSigno = "";
        reescribible = 1;
        dato.setNumero(0);
        jLNumero.setText("0");
        jLOperaciones.setText("");
    }//GEN-LAST:event_jBCActionPerformed

    private void jBMrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMrActionPerformed
        jLNumero.setText(String.valueOf(dato.getValorMemoria()));
        reescribible = 1;
    }//GEN-LAST:event_jBMrActionPerformed

    private void jBmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBmMouseEntered
        jBm.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jBmMouseEntered

    private void jBmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBmMouseExited
        jBm.setBackground(new Color(25, 24, 24));
    }//GEN-LAST:event_jBmMouseExited

    private void jBmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmActionPerformed
        jBmc.setEnabled(true);
        jBMr.setEnabled(true);
        jBmc.setBackground(new Color(25, 24, 24));
        jBMr.setBackground(new Color(25, 24, 24));
        controlMemoria = 1;
        reescribible = 1;
        dato.setValorMemoria(jLNumero.getText());
    }//GEN-LAST:event_jBmActionPerformed

    private void jBmMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmMenosActionPerformed

        jBmc.setEnabled(true);
        jBMr.setEnabled(true);
        jBmc.setBackground(new Color(25, 24, 24));
        jBMr.setBackground(new Color(25, 24, 24));
        controlMemoria = 1;
        dato.operacionMemoria(2, jLNumero.getText());
    }//GEN-LAST:event_jBmMenosActionPerformed

    private void jBmcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmcActionPerformed

        jLNumero.setText("0");

        jBmc.setEnabled(false);
        jBMr.setEnabled(false);
        jBmc.setBackground(new Color(0, 0, 0));
        jBMr.setBackground(new Color(0, 0, 0));
        controlMemoria = 0;
    }//GEN-LAST:event_jBmcActionPerformed

    private void jBModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModuloActionPerformed

        reescribible = 1;

        if (ultimoSigno.equals("")) {
            dato.setNumero(Double.parseDouble(jLNumero.getText()));
            System.out.println("datico" + dato.getNumero());
            jLOperaciones.setText("(" + jLNumero.getText() + " %");
            reescribible = 1;
        } else if (reescribible != 0) {
            System.out.println("-----------------------------------");
            System.out.println("datico" + dato.getNumero());
            System.out.println("ultimo signo" + ultimoSigno);
            jLOperaciones.setText(jLOperaciones.getText() + jLNumero.getText() + ") % ");
            jLNumero.setText(dato.operaciones(Double.parseDouble(jLNumero.getText()), ultimoSigno));

        }

        ultimoSigno = "%";
    }//GEN-LAST:event_jBModuloActionPerformed

    private void jBSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSumaActionPerformed

        reescribible = 1;
        System.out.println("dasdasd " + jLOperaciones.getText());

        if (ultimoSigno.equals("")) {
            dato.setNumero(Double.parseDouble(jLNumero.getText()));
            System.out.println("datico" + dato.getNumero());

            if (operacionNobasica == 1) {
                jLOperaciones.setText(jLNumero.getText() + " +");
                jLNumero.setText(dato.operaciones(Double.parseDouble(jLNumero.getText()), ultimoSigno));
                reescribible = 1;
                System.out.println("yyyyy1");
            } else {
                jLOperaciones.setText(jLNumero.getText() + " +");
                reescribible = 1;
                System.out.println("jjjjjj");
            }

        } else if (reescribible != 0) {
            System.out.println("-----------------------------------");
            System.out.println("datico" + dato.getNumero());
            System.out.println("ultimo signo" + ultimoSigno);
            if (operacionNobasica == 1) {
                jLOperaciones.setText(jLOperaciones.getText() + jLNumero.getText()+" +");
            jLNumero.setText(dato.operaciones(Double.parseDouble(jLNumero.getText()),ultimoSigno));              
                System.out.println("yyyyy2");
                operacionNobasica = 0;
            } else {
                jLOperaciones.setText(jLOperaciones.getText() + jLNumero.getText() + " +");
                jLNumero.setText(dato.operaciones(Double.parseDouble(jLNumero.getText()), ultimoSigno));
                System.out.println("toyssss");
            }
//            jLOperaciones.setText(jLOperaciones.getText() +jLNumero.getText()+ " +");
//            jLNumero.setText(dato.operaciones(Double.parseDouble(jLNumero.getText()),ultimoSigno));

        }

        ultimoSigno = "+";

    }//GEN-LAST:event_jBSumaActionPerformed

    private void jB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB9ActionPerformed

        if (reescribible == 1) {
            reescribible = 0;
            jLNumero.setText("9");
        } else {
            jLNumero.setText(jLNumero.getText() + "9");
        }

    }//GEN-LAST:event_jB9ActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed

        if (reescribible == 1) {
            reescribible = 0;
            jLNumero.setText("5");
        } else {
            jLNumero.setText(jLNumero.getText() + "5");
        }

    }//GEN-LAST:event_jB5ActionPerformed

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB6ActionPerformed

        if (reescribible == 1) {
            reescribible = 0;
            jLNumero.setText("6");
        } else {
            jLNumero.setText(jLNumero.getText() + "6");
        }

    }//GEN-LAST:event_jB6ActionPerformed

    private void jBCeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCeActionPerformed
        jLNumero.setText("0");
        reescribible = 1;
        ultimoSigno = "";
//        dato.setResultado(0);
    }//GEN-LAST:event_jBCeActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed

        if (reescribible == 1) {
            reescribible = 0;
            jLNumero.setText("1");

        } else {
            jLNumero.setText(jLNumero.getText() + "1");
        }
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed

        if (reescribible == 1) {
            reescribible = 0;
            jLNumero.setText("3");
        } else {
            jLNumero.setText(jLNumero.getText() + "3");
        }
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB0ActionPerformed

        if (reescribible == 1) {
            reescribible = 0;
            jLNumero.setText("0");
        } else {
            jLNumero.setText(jLNumero.getText() + "0");
        }
    }//GEN-LAST:event_jB0ActionPerformed

    private void jBMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMultiplicacionActionPerformed
        reescribible = 1;

        if (ultimoSigno.equals("")) {
            dato.setNumero(Double.parseDouble(jLNumero.getText()));
            System.out.println("datico" + dato.getNumero());
            jLOperaciones.setText(jLNumero.getText() + " x");
            reescribible = 1;
        } else if (reescribible != 0) {
            System.out.println("-----------------------------------");
            System.out.println("datico" + dato.getNumero());
            System.out.println("ultimo signo" + ultimoSigno);
            jLOperaciones.setText(jLOperaciones.getText() + jLNumero.getText() + " x");
            jLNumero.setText(dato.operaciones(Double.parseDouble(jLNumero.getText()), ultimoSigno));

        }

        ultimoSigno = "*";
    }//GEN-LAST:event_jBMultiplicacionActionPerformed

    private void jBDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDivisionActionPerformed
        reescribible = 1;

        if (ultimoSigno.equals("")) {
            dato.setNumero(Double.parseDouble(jLNumero.getText()));
            System.out.println("datico" + dato.getNumero());
            jLOperaciones.setText(jLNumero.getText() + " ÷");
            reescribible = 1;
        } else if (reescribible != 0) {
            System.out.println("-----------------------------------");
            System.out.println("datico" + dato.getNumero());
            System.out.println("ultimo signo" + ultimoSigno);
            jLOperaciones.setText(jLOperaciones.getText() + jLNumero.getText() + " ÷");
            jLNumero.setText(dato.operaciones(Double.parseDouble(jLNumero.getText()), ultimoSigno));

        }

        ultimoSigno = "/";
    }//GEN-LAST:event_jBDivisionActionPerformed

    private void jBComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBComaActionPerformed
        String cadena;

        cadena = jLNumero.getText(); // me guarda todo lo que tenga en la pantalla
        reescribible = 0;

        if (cadena.length() <= 0) { // mira si la cadena de la pantalla esta vacia
            jLNumero.setText("0.");

        } else {

            if (!dato.existePunto(jLNumero.getText())) { // si no existe un punto en la pantalla
                jLNumero.setText(jLNumero.getText() + "."); // le pone un punto 
            }
        }
    }//GEN-LAST:event_jBComaActionPerformed

    private void jBRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRaizActionPerformed
        reescribible = 1;
        operacionNobasica = 1;

        String temporal = jLNumero.getText();

        if (ultimoSigno.equals("")) {
            dato.setNumero(Double.parseDouble(jLNumero.getText()));
            System.out.println("datico" + dato.getNumero());
            jLNumero.setText(dato.operaciones(Double.parseDouble(jLNumero.getText()), "√"));
            jLOperaciones.setText(" √(" + temporal + ")");
            reescribible = 1;
        } else if (reescribible != 0) {
            System.out.println("-----------------------------------");
            System.out.println("datico" + dato.getNumero());
            System.out.println("ultimo signo" + ultimoSigno);
            jLOperaciones.setText(" √" + jLOperaciones.getText());
                        dato.operaciones(Double.parseDouble(temporal), "√");
            jLNumero.setText(dato.operaciones(Double.parseDouble(jLNumero.getText()), ultimoSigno));

        }

//        ultimoSigno = "√";
    }//GEN-LAST:event_jBRaizActionPerformed

    private void jBElevarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBElevarActionPerformed

        reescribible = 1;
        operacionNobasica = 1;

        String temporal = jLNumero.getText();

        if (ultimoSigno.equals("")) {
            dato.setNumero(Double.parseDouble(jLNumero.getText()));
            System.out.println("datico" + dato.getNumero());
            jLNumero.setText(dato.operaciones(Double.parseDouble(jLNumero.getText()), "^"));
            jLOperaciones.setText(" sqr(" + temporal + ")");
            reescribible = 1;
        } else if (reescribible != 0) {
            System.out.println("ultimo signo= " + ultimoSigno);
            System.out.println("-----------------------------------");
            System.out.println("datico" + dato.getNumero());
            System.out.println("ultimo signo" + ultimoSigno);
            jLOperaciones.setText(jLOperaciones.getText() + " sqr(" + temporal);
            dato.operaciones(Double.parseDouble(temporal), "^");
            jLNumero.setText(dato.operaciones(Double.parseDouble(jLNumero.getText()), ultimoSigno));

        }

//        ultimoSigno="^";
    }//GEN-LAST:event_jBElevarActionPerformed

    private void jBBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarActionPerformed

        String cadena;
        cadena = jLNumero.getText();
        if (cadena.length() > 1) {

            cadena = cadena.substring(0, cadena.length() - 1);
            jLNumero.setText(cadena);
        } else {
            jLNumero.setText("0");
        }
    }//GEN-LAST:event_jBBorrarActionPerformed

    private void jBIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIgualActionPerformed

        if (!ultimoSigno.equals("")) {
            jLNumero.setText(dato.operaciones(Double.parseDouble(jLNumero.getText()), ultimoSigno));
            jLOperaciones.setText("");
            ultimoSigno = "";
        } else {
            jLNumero.setText(String.valueOf(dato.getNumero()));
        }

    } //GEN-LAST:event_jBIgualActionPerformed

    private void jB7KeyPressed(java.awt.event.KeyEvent evt) { //GEN-FIRST:event_jB7KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_7) {
            jLNumero.setText("7");
            System.out.println("asdasdad");
        }

        System.out.println(evt.getKeyChar());
    } //GEN-LAST:event_jB7KeyPressed

    private void jBFraccionarActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jBFraccionarActionPerformed

        reescribible = 1;
        operacionNobasica = 1;

        String temporal = jLNumero.getText();

        if (ultimoSigno.equals("")) {
            dato.setNumero(Double.parseDouble(jLNumero.getText()));
            System.out.println("datico" + dato.getNumero());
            jLNumero.setText(dato.operaciones(Double.parseDouble(jLNumero.getText()), "1/x"));
            jLOperaciones.setText(" 1/(" + temporal + ")");
            reescribible = 1;
        } else if (reescribible != 0) {
            System.out.println("-----------------------------------");
            System.out.println("datico" + dato.getNumero());
            System.out.println("ultimo signo" + ultimoSigno);
            jLOperaciones.setText(" 1/(" + jLOperaciones.getText());
            jLNumero.setText(dato.operaciones(Double.parseDouble(jLNumero.getText()), ultimoSigno));

        }

        ultimoSigno = "1/x";
    } //GEN-LAST:event_jBFraccionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                 try {
//                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//                } catch (Exception e) {
//                }
                new interfazCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB0;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBC;
    private javax.swing.JButton jBCe;
    private javax.swing.JButton jBCerrar;
    private javax.swing.JButton jBComa;
    private javax.swing.JButton jBDivision;
    private javax.swing.JButton jBElevar;
    private javax.swing.JButton jBFraccionar;
    private javax.swing.JButton jBIgual;
    private javax.swing.JButton jBMinimizar;
    private javax.swing.JButton jBModulo;
    private javax.swing.JButton jBMr;
    private javax.swing.JButton jBMultiplicacion;
    private javax.swing.JButton jBNegacion;
    private javax.swing.JButton jBRaiz;
    private javax.swing.JButton jBResta;
    private javax.swing.JButton jBSuma;
    private javax.swing.JButton jBm;
    private javax.swing.JButton jBmMas;
    private javax.swing.JButton jBmMenos;
    private javax.swing.JButton jBmc;
    private javax.swing.JLabel jLNumero;
    private javax.swing.JLabel jLOperaciones;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
